export const ALL_PRODUCT_REQUESTS = 'ALL_PRODUCT_REQUESTS'
export const ALL_PRODUCT_SUCCESS = 'ALL_PRODUCT_SUCCESS'
export const ALL_PRODUCT_FAIL = 'ALL_PRODUCT_FAIL'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'

const SINGLE_PRODUCT_REQUEST = 'SINGLE_PRODUCT_REQUEST'
const CREATE_PRODUCT = 'CREATE_PRODUCT'
const GET_ALL_PRODUCT_REVIEWS = 'GET_ALL_PRODUCT_REVIEWS'
const GIVE_PRODUCT_REVIEW = 'GIVE_PRODUCT_REVIEW'
